export const mealRecipes: Record<string, string> = {
  "lb-1": "Mélangez l’avoine, le chia et le lait végétal. Laissez gonfler, puis servez.",
  "lb-2": "Pochez les œufs dans une eau frémissante. Déposez-les sur le pain grillé.",
  "lb-3": "Rincez les baies et ajoutez-les au skyr. Servez frais.",
  "lb-4": "Faites tomber les épinards avec les tomates. Ajoutez les blancs battus et cuisez à feu doux.",
  "lb-5": "Saupoudrez le fromage blanc de cannelle et ajoutez les amandes.",
  "lb-6": "Étalez la ricotta sur le seigle, puis ajoutez de fines rondelles de concombre.",
  "lb-7": "Mixez les épinards, le concombre et la pomme avec un peu d’eau.",
  "lb-8": "Cuisez le son d’avoine avec de l’eau ou du lait. Incorporez le lin moulu.",
  "lb-9": "Émiettez le tofu et réchauffez-le à la poêle avec le curcuma et les herbes.",
  "lb-10": "Tranchez l’avocat et servez-le avec le saumon fumé.",
  "lb-11": "Réchauffez la galette, ajoutez le jambon de dinde et repliez.",
  "lb-12": "Découpez le pamplemousse et servez-le avec le yaourt grec.",
  "lb-13": "Mélangez le chia et le lait d’amande. Réfrigérez au moins 2 heures.",
  "lb-14": "Étalez une fine couche de tahini sur le pain essène.",
  "lb-15": "Infusez le café vert ou fouettez le matcha dans de l’eau chaude, sans sucre.",
  "ll-1": "Grillez le poulet avec les herbes jusqu’à cuisson complète. Servez avec les haricots vapeur.",
  "ll-2": "Cuisez le quinoa, rôtissez le cabillaud et faites sauter les courgettes.",
  "ll-3": "Cuisez l’œuf dur, puis assemblez-le avec le thon égoutté et les épinards rincés.",
  "ll-4": "Cuisez le steak à cœur. Écrasez la patate douce cuite avec un peu d’eau de cuisson.",
  "ll-5": "Cuisez le saumon et les brocolis à la vapeur. Assaisonnez au moment de servir.",
  "ll-6": "Mijotez les lentilles corail et les carottes avec de l’eau et le cumin.",
  "ll-7": "Faites sauter les poivrons et le soja, puis ajoutez les crevettes et cuisez-les complètement.",
  "ll-8": "Cuisez le riz complet. Faites revenir la dinde jusqu’à cuisson complète et assemblez.",
  "ll-9": "Mélangez les pois chiches cuits, les tomates coupées, le persil et le jus de citron.",
  "ll-10": "Rôtissez la daurade au four. Faites mijoter le fenouil avec le thym.",
  "ll-11": "Marinez le tofu au gingembre, grillez-le et accompagnez-le d’asperges cuites.",
  "ll-12": "Mijotez les haricots cuits et le maïs avec de la tomate et les épices.",
  "ll-13": "Cuisez le filet mignon et faites revenir les champignons avec le persil.",
  "ll-14": "Coupez le concombre et la feta. Mélangez et ajoutez l’origan.",
  "ll-15": "Mixez tomates, concombre et poivron avec un filet d’huile d’olive. Servez frais.",
  "ld-1": "Cuisez le potimarron et les carottes dans l’eau, puis mixez sans crème.",
  "ld-2": "Pochez le lieu dans le court-bouillon et accompagnez-le de poireaux fondants.",
  "ld-3": "Cuisez les œufs battus avec les herbes et servez avec la salade rincée.",
  "ld-4": "Mijotez les shiitakés dans un bouillon parfumé, puis ajoutez le tofu en dés.",
  "ld-5": "Cuisez le poulet et le chou-fleur à la vapeur jusqu’à cuisson complète.",
  "ld-6": "Cuisez courgettes, épinards et céleri dans l’eau, puis mixez.",
  "ld-7": "Cuisez le colin à la vapeur avec une julienne de carottes et de panais.",
  "ld-8": "Rôtissez les aubergines sur du papier cuisson, puis ajoutez l’ail et la coriandre.",
  "ld-9": "Enfermez truite, citron vert et épinards dans une papillote. Cuisez au four.",
  "ld-10": "Cuisez les lentilles, égouttez et mélangez avec l’échalote finement coupée.",
  "ld-11": "Coupez le concombre en petits dés. Mélangez avec le yaourt et la menthe.",
  "ld-12": "Grillez le veau et servez avec le céleri-rave cuit puis mixé.",
  "ld-13": "Mijotez les haricots blancs cuits et les blettes dans un bouillon de légumes.",
  "ld-14": "Tranchez très finement les courgettes. Ajoutez le citron et le parmesan.",
  "ld-15": "Infusez la camomille et la verveine dans l’eau chaude, sans sucre.",
  "ls-1": "Lavez et coupez la pomme. Accompagnez-la des amandes.",
  "ls-2": "Saupoudrez le skyr nature de cannelle et servez frais.",
  "ls-3": "Coupez les crudités en bâtonnets et servez avec le houmous.",
  "ls-4": "Cuisez l’œuf dur, refroidissez et ajoutez une pincée de sel aux herbes.",
  "ls-5": "Servez les deux carrés de chocolat tels quels.",
  "ls-6": "Lavez et coupez la poire. Infusez le thé vert à côté.",
  "ls-7": "Ajoutez les graines de grenade au fromage blanc.",
  "ls-8": "Servez trois noix du Brésil, sans préparation supplémentaire.",
  "ls-9": "Cuisez les edamames à la vapeur et salez légèrement. Mangez uniquement les graines.",
  "ls-10": "Tranchez le radis noir et garnissez-le de fromage frais.",
  "ls-11": "Secouez la whey avec la quantité d’eau indiquée sur son emballage.",
  "ls-12": "Étalez la purée d’amande sur la galette de riz.",
  "ls-13": "Épluchez le kiwi, tranchez-le et ajoutez le chia.",
  "ls-14": "Mélangez le cottage cheese avec la ciboulette ciselée.",
  "ls-15": "Infusez le gingembre et la menthe dans l’eau chaude. Ajoutez le citron.",
  "gb-1": "Cuisez l’avoine, puis incorporez le beurre de cacahuète et les rondelles de banane.",
  "gb-2": "Brouillez les œufs. Servez sur le toast grillé avec l’avocat.",
  "gb-3": "Ajoutez le granola au yaourt grec, puis un filet de miel.",
  "gb-4": "Mélangez farine d’avoine, œuf et lait. Cuisez de petits pancakes et ajoutez le sirop.",
  "gb-5": "Ouvrez le bagel, étalez le fromage frais et ajoutez le saumon fumé.",
  "gb-6": "Mixez lait, avoine, banane et whey jusqu’à obtenir une texture homogène.",
  "gb-7": "Trempez le pain dans un mélange de lait et d’œuf. Dorez à la poêle et ajoutez les amandes.",
  "gb-8": "Faites revenir les champignons, ajoutez les œufs et le cheddar. Servez avec le pain.",
  "gb-9": "Étalez la purée d’amande et la compote sur le pain grillé.",
  "gb-10": "Mélangez le muesli et les fruits secs avec le lait. Laissez gonfler quelques minutes.",
  "gb-11": "Garnissez le wrap d’œufs brouillés, de haricots cuits et de fromage, puis roulez.",
  "gb-12": "Mélangez avoine et lait. Réfrigérez une nuit et ajoutez chocolat et graines de courge.",
  "gb-13": "Tartinez la brioche de beurre et de confiture.",
  "gb-14": "Ajoutez au cottage cheese les dattes dénoyautées et les pistaches.",
  "gb-15": "Réchauffez le lait et ajoutez le café ou le cacao. Remuez avant de servir.",
  "gl-1": "Rôtissez les bâtonnets de patate douce au four et cuisez le steak à votre convenance.",
  "gl-2": "Cuisez le riz et le saumon à la poêle. Ajoutez une sauce au yaourt et à l’aneth.",
  "gl-3": "Cuisez les pâtes et le poulet. Mélangez avec le pesto et le parmesan.",
  "gl-4": "Mijotez bœuf, légumes et pois chiches cuits. Servez sur la semoule réhydratée.",
  "gl-5": "Mijotez le poulet avec les pruneaux. Ajoutez les amandes grillées et servez avec la semoule.",
  "gl-6": "Faites sauter le riz cuit avec le poulet et les légumes. Ajoutez un œuf bien cuit.",
  "gl-7": "Cuisez le quinoa. Saisissez le thon et ajoutez l’avocat en dés.",
  "gl-8": "Assemblez le riz cuit, le bœuf cuit, les haricots rouges cuits et le cheddar.",
  "gl-9": "Mijotez le poulet avec les épices et le lait de coco. Servez avec le riz jasmin.",
  "gl-10": "Réchauffez la cuisse confite au four et faites sauter les pommes de terre à l’ail.",
  "gl-11": "Mijotez le jarret avec les lentilles et les carottes jusqu’à ce que la viande soit tendre.",
  "gl-12": "Alternez pâtes, sauce bolognaise et béchamel. Gratinez au four jusqu’à cuisson complète.",
  "gl-13": "Faites cuire le porc dans la sauce caramel. Servez avec le riz gluant et le sésame.",
  "gl-14": "Cuisez les gnocchis et nappez-les de gorgonzola fondu. Ajoutez les noix.",
  "gl-15": "Garnissez la baguette de rôti de bœuf, de cornichons et de mayonnaise.",
  "gd-1": "Enrobez le cabillaud d’amandes concassées et cuisez au four. Servez avec la purée.",
  "gd-2": "Cuisez le riz en ajoutant le bouillon progressivement. Incorporez les cèpes et le parmesan.",
  "gd-3": "Mijotez bœuf, haricots cuits, tomate et maïs. Servez avec les tortilla chips.",
  "gd-4": "Rôtissez le poulet jusqu’à cuisson complète et accompagnez-le de pommes de terre sautées.",
  "gd-5": "Mijotez les châtaignes cuites dans le lait de coco, mixez et ajoutez les graines toastées.",
  "gd-6": "Tranchez les pommes de terre, couvrez de lait et de comté, puis cuisez au four.",
  "gd-7": "Faites sauter le bœuf et les udon cuits. Assaisonnez avec la sauce soja et le sésame.",
  "gd-8": "Cuisez les lardons et les pommes de terre, puis ajoutez les œufs battus et la ciboulette.",
  "gd-9": "Grillez la truite. Préparez la polenta au beurre et servez avec les haricots verts.",
  "gd-10": "Alternez canard confit effiloché et purée de patate douce, puis gratinez.",
  "gd-11": "Cuisez le quinoa et le tofu. Ajoutez la sauce à l’arachide et l’avocat.",
  "gd-12": "Mijotez l’agneau, les légumes et le frik dans le bouillon jusqu’à cuisson complète.",
  "gd-13": "Rôtissez le flétan avec le beurre noisette. Servez avec le riz sauvage cuit.",
  "gd-14": "Mijotez les pois chiches cuits avec les tomates et les saucisses de volaille bien cuites.",
  "gd-15": "Cuisez la semoule dans le lait d’amande avec les raisins, puis laissez prendre.",
  "gs-1": "Garnissez deux tranches de pain de beurre de cacahuète et de confiture.",
  "gs-2": "Mélangez les amandes, noix, noisettes et raisins secs.",
  "gs-3": "Mixez la whey avec le lait et la banane.",
  "gs-4": "Dénoyautez les dattes et garnissez-les de beurre d’amande.",
  "gs-5": "Ajoutez miel et noix au yaourt grec.",
  "gs-6": "Mélangez avoine, beurre d’oléagineux et chocolat, puis pressez en barre et réfrigérez.",
  "gs-7": "Épluchez les bananes et servez avec les carrés de chocolat.",
  "gs-8": "Tranchez le comté et servez avec le pain aux noix.",
  "gs-9": "Servez les biscuits à l’avoine avec un verre de lait.",
  "gs-10": "Écrasez l’avocat et étalez-le sur le pain grillé.",
  "gs-11": "Mixez mangue, pulpe de fruit de la passion et lait de coco.",
  "gs-12": "Mixez dattes dénoyautées, cacao et graines de tournesol. Formez de petites boules.",
  "gs-13": "Ajoutez l’ananas coupé et les noix de pécan au cottage cheese.",
  "gs-14": "Toastez la brioche et nappez-la d’un peu de chocolat fondu.",
  "gs-15": "Mélangez lin et chia au lait d’avoine. Réfrigérez au moins 2 heures.",
  "mb-1": "Mélangez muesli, yaourt nature et fruits frais coupés.",
  "mb-2": "Cuisez les œufs à la coque et servez avec le seigle grillé.",
  "mb-3": "Cuisez l’avoine dans l’eau et le lait, puis ajoutez pomme râpée et cannelle.",
  "mb-4": "Écrasez l’avocat avec le citron. Étalez sur le pain et ajoutez le sésame.",
  "mb-5": "Battez le fromage blanc et ajoutez les myrtilles et les noix.",
  "mb-6": "Cuisez les œufs battus avec les herbes et servez avec les tomates.",
  "mb-7": "Écrasez la banane, mélangez avec avoine et œuf, puis cuisez de petits pancakes.",
  "mb-8": "Coupez les fruits de saison et servez avec le yaourt de brebis.",
  "mb-9": "Frottez le pain grillé avec la tomate. Ajoutez l’huile d’olive et le jambon.",
  "mb-10": "Mélangez chia et lait de noisette. Réfrigérez 2 heures et ajoutez les fraises.",
  "mb-11": "Préparez un petit blini de sarrasin et garnissez-le de saumon fumé.",
  "mb-12": "Mixez banane, fraises, yaourt et épinards rincés.",
  "mb-13": "Tartinez les biscottes de beurre et d’un peu de miel.",
  "mb-14": "Garnissez la galette d’épeautre de cottage cheese et de radis émincés.",
  "mb-15": "Préparez le café filtre ou faites infuser le thé Earl Grey.",
  "ml-1": "Rôtissez le poulet, cuisez le riz et faites revenir les courgettes.",
  "ml-2": "Grillez le saumon. Mixez les pois cassés cuits et accompagnez de carottes vapeur.",
  "ml-3": "Cuisez les pâtes et mélangez-les avec le coulis, le basilic et la mozzarella.",
  "ml-4": "Cuisez le steak à cœur, rôtissez les pommes grenaille et servez avec la salade.",
  "ml-5": "Mijotez la dinde et les légumes dans le bouillon. Servez avec la semoule.",
  "ml-6": "Cuisez le quinoa, rôtissez les pois chiches cuits et ajoutez avocat et sauce tahini.",
  "ml-7": "Cuisez le merlu au four et accompagnez de riz pilaf et de poivrons grillés.",
  "ml-8": "Marinez les crevettes au gingembre. Faites-les sauter et ajoutez les soba cuites.",
  "ml-9": "Mijotez le veau avec les carottes et les petits pois. Ajoutez la coriandre.",
  "ml-10": "Assemblez thon, haricots verts cuits et œuf dur avec les légumes de la salade.",
  "ml-11": "Cuisez le porc au curry et servez avec riz basmati et brocolis vapeur.",
  "ml-12": "Mijotez les lentilles jaunes avec les épices. Servez avec un naan complet réchauffé.",
  "ml-13": "Rôtissez la canette et accompagnez-la de carottes cuites puis mixées au cumin.",
  "ml-14": "Cuisez les pommes de terre, ajoutez les œufs battus et dorez la tortilla. Servez avec la roquette.",
  "ml-15": "Préparez le bœuf très frais, hachez au couteau, assaisonnez et servez immédiatement avec la salade.",
  "md-1": "Cuisez le cabillaud vapeur et servez avec les poireaux fondants et les pommes de terre.",
  "md-2": "Cuisez panais, carotte et courge dans le bouillon, mixez et ajoutez les croûtons.",
  "md-3": "Faites revenir les champignons, ajoutez les œufs et roulez l’omelette. Servez avec la salade.",
  "md-4": "Pochez le poulet dans le bouillon jusqu’à cuisson complète. Servez avec le riz brun.",
  "md-5": "Mijotez les légumes et les pois chiches cuits dans un bouillon, puis ajoutez les herbes.",
  "md-6": "Cuisez la truite à la poêle. Faites tomber les épinards avec un peu de crème légère.",
  "md-7": "Mélangez les lentilles et les carottes cuites, puis ajoutez la feta.",
  "md-8": "Déposez les courgettes dans un plat. Ajoutez parmesan et chapelure, puis gratinez.",
  "md-9": "Mijotez le bok choy dans le bouillon. Ajoutez les crevettes et cuisez-les complètement.",
  "md-10": "Faites sauter tofu et légumes, puis ajoutez les graines de sésame.",
  "md-11": "Grillez la dinde et servez avec le potimarron cuit puis mixé.",
  "md-12": "Mijotez les légumes et les haricots cuits dans un bouillon parfumé.",
  "md-13": "Enfermez le colin et le romarin en papillote. Cuisez au four avec les tomates.",
  "md-14": "Mélangez le quinoa cuit et refroidi, les herbes, le concombre et la grenade.",
  "md-15": "Cuisez les pommes coupées avec un peu d’eau, puis écrasez. Servez avec la tisane.",
  "ms-1": "Lavez et coupez la pomme. Servez avec les noisettes.",
  "ms-2": "Incorporez une cuillère de miel au yaourt nature.",
  "ms-3": "Dénoyautez les dattes et servez avec les amandes.",
  "ms-4": "Ajoutez la compote de poires au fromage blanc.",
  "ms-5": "Servez le chocolat avec le thé blanc infusé.",
  "ms-6": "Étalez le fromage de chèvre frais sur le pain complet.",
  "ms-7": "Épluchez la banane et servez avec la menthe infusée.",
  "ms-8": "Coupez les crudités et servez avec le houmous.",
  "ms-9": "Toastez brièvement les graines à sec, puis laissez refroidir.",
  "ms-10": "Mixez les myrtilles avec le lait d’amande.",
  "ms-11": "Cuisez l’œuf dur, refroidissez et servez avec la tomate et le sel aux herbes.",
  "ms-12": "Coupez la pêche en dés et ajoutez-la au cottage cheese.",
  "ms-13": "Étalez une fine couche de purée de noisette sur la galette de maïs.",
  "ms-14": "Rincez le raisin et servez avec les noix.",
  "ms-15": "Infusez le rooibos et servez avec le biscuit à l’épeautre."
};
