import React, {useState} from 'react';
import type {UserProfile} from '../types';
import {localDate} from '../services/dates';
import {parseLocalizedNumber} from '../services/numberInput';
import {nutritionTarget} from '../services/nutritionTarget';
export function AmbitionPlan({profile,onUpdateProfile}:{profile:UserProfile;onUpdateProfile?:(p:Partial<UserProfile>)=>void}) {
 const [weight,setWeight]=useState(profile.fourWeeksTargetWeight===undefined?(profile.customFourWeeksGoalKg===undefined?'':String(+(profile.currentWeight+profile.customFourWeeksGoalKg).toFixed(1))):String(profile.fourWeeksTargetWeight));
 const [date,setDate]=useState(profile.ambitionDeadline||'');const [message,setMessage]=useState('');
 const c=(fr:string,en:string,ar:string)=>profile.preferredLanguage==='ar'?ar:profile.preferredLanguage==='en'?en:fr;
 const goal=profile.weightGoal||'lose';const target=nutritionTarget(profile);
 const reached=goal==='lose'?profile.currentWeight<=profile.targetWeight:goal==='gain'?profile.currentWeight>=profile.targetWeight:false;
 return <section id="ambition-plan" className="scroll-mt-24 rounded-3xl border border-orange-300 dark:border-orange-700 bg-orange-50 dark:bg-slate-900 p-5 space-y-4">
 <h3 className="text-xl font-bold">{c('Mon ambition & mon plan d’action','My ambition & action plan','طموحي وخطة عملي')}</h3>
 <p>{c('Choisissez votre poids souhaité dans 4 semaines et votre date souhaitée pour l’objectif final.','Choose your desired weight in 4 weeks and your desired date for the final goal.','اختر الوزن المرغوب خلال 4 أسابيع والتاريخ المرغوب لهدفك النهائي.')}</p>
 {reached&&<div role="status" className="rounded-xl bg-emerald-100 dark:bg-emerald-950 p-4 space-y-2"><strong>{c('Bravo, votre objectif est atteint !','Well done, your goal is reached!','أحسنت، لقد وصلت إلى هدفك!')}</strong><p>{c('La stabilisation vous aide à conserver vos progrès. Vos repas et votre suivi s’adapteront à ce nouvel objectif.','Maintenance helps preserve your progress. Your meals and tracking will adapt to this new goal.','يساعد تثبيت الوزن على الحفاظ على تقدمك وستتكيف الوجبات والمتابعة مع هذا الهدف.')}</p><button className="action-primary rounded-xl p-3" onClick={()=>onUpdateProfile?.({weightGoal:'maintain',targetWeight:profile.currentWeight,customFourWeeksGoalKg:0,fourWeeksTargetWeight:profile.currentWeight,dailyCalorieTarget:nutritionTarget({...profile,weightGoal:'maintain'}).calories})}>{c('Passer à la stabilisation','Switch to maintenance','الانتقال إلى تثبيت الوزن')}</button></div>}
 <form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const n=parseLocalizedNumber(weight);if(n===null||n<30||n>300){setMessage(c('Saisissez un poids entre 30 et 300 kg.','Enter a weight between 30 and 300 kg.','أدخل وزناً بين 30 و300 كغ.'));return;}if((goal==='lose'&&n>=profile.currentWeight)||(goal==='gain'&&n<=profile.currentWeight)||(goal==='maintain'&&Math.abs(n-profile.currentWeight)>2)){setMessage(c('Ce poids ne correspond pas à votre objectif actif.','This weight does not match your active goal.','هذا الوزن لا يتوافق مع هدفك الحالي.'));return;}if(date&&date<=localDate()){setMessage(c('Choisissez une date future.','Choose a future date.','اختر تاريخاً مستقبلياً.'));return;}onUpdateProfile?.({customFourWeeksGoalKg:+(n-profile.currentWeight).toFixed(1),fourWeeksTargetWeight:n,ambitionStartedAt:localDate(),ambitionDeadline:date||undefined});setMessage(c('Ambition enregistrée. Chaque petit progrès compte !','Ambition saved. Every small step counts!','تم حفظ طموحك. كل تقدم صغير مهم!'));}}>
 <label className="text-sm font-semibold">{c('Poids souhaité dans 4 semaines (kg)','Desired weight in 4 weeks (kg)','الوزن المرغوب خلال 4 أسابيع (كغ)')}<input className="mt-2 w-full rounded-xl border p-3" inputMode="decimal" value={weight} onChange={e=>setWeight(e.target.value)} placeholder={`${c('Exemple','Example','مثال')}: ${+(profile.currentWeight+(goal==='gain'?1:goal==='maintain'?0:-1)).toFixed(1)}`} required/></label>
 <label className="text-sm font-semibold">{c('Date souhaitée pour l’objectif final','Desired date for the final goal','التاريخ المرغوب لهدفي النهائي')}<input className="mt-2 w-full rounded-xl border p-3" type="date" min={localDate()} value={date} onChange={e=>setDate(e.target.value)}/></label>
 <button className="action-primary rounded-xl p-3 font-bold" type="submit">{c('Enregistrer mon ambition','Save my ambition','حفظ طموحي')}</button><p role="status">{message}</p></form>
 <p className="text-sm">{c(`Votre repère alimentaire est d’environ ${target.calories} kcal/jour, basé sur ${target.measured?'votre métabolisme InBody':'vos mesures'} et votre objectif.`,`Your food guide is about ${target.calories} kcal/day, based on ${target.measured?'your InBody metabolism':'your measurements'} and your goal.`,`هدفك الغذائي التقريبي ${target.calories} سعرة يومياً بناءً على قياساتك وهدفك.`)}</p>
 <div className="grid sm:grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-white dark:bg-slate-800 p-4"><strong>{c('🥗 Mes repas','🥗 My meals','🥗 وجباتي')}</strong><p>{goal==='gain'?c('Mangez régulièrement et ajoutez une collation nourrissante selon votre faim.','Eat regularly and add a nourishing snack according to hunger.','نظم وجباتك وأضف وجبة خفيفة مغذية حسب جوعك.'):goal==='maintain'?c('Gardez vos habitudes et ajustez les portions selon votre faim et l’évolution du poids.','Keep your habits and adjust portions based on hunger and weight changes.','حافظ على عاداتك وعدّل الكميات حسب الجوع وتغير الوزن.'):c('Associez légumes, protéines et féculents; suivez vos portions sans sauter de repas.','Combine vegetables, protein and starches; track portions without skipping meals.','اجمع الخضار والبروتين والنشويات وتابع الكميات دون تفويت الوجبات.')}</p></div><div className="rounded-xl bg-white dark:bg-slate-800 p-4"><strong>{c('🚶 Activité & suivi','🚶 Activity & tracking','🚶 نشاطي ومتابعتي')}</strong><p>{c('Bougez régulièrement à votre niveau. Enregistrez vos repas et vos pesées, puis comparez vos progrès chaque semaine.','Move regularly at your own level. Record meals and weigh-ins, then review progress weekly.','تحرك بانتظام حسب قدرتك وسجّل وجباتك ووزنك وراجع تقدمك أسبوعياً.')}</p></div></div>
 <p className="text-xs text-slate-600 dark:text-slate-300">{c('Votre ambition est un souhait personnel. Le résultat et la date ne sont pas garantis. Un objectif rapide nécessite un accompagnement adapté.','Your ambition is a personal wish. Results and dates are not guaranteed. Rapid goals require appropriate support.','طموحك رغبة شخصية؛ النتيجة والتاريخ غير مضمونين، والأهداف السريعة تحتاج إلى متابعة مناسبة.')}</p></section>;
}
