#!/usr/bin/env python3
import json
import os

os.makedirs("src/services/translations", exist_ok=True)

# 1. Italian mappings
IT_MAPPINGS = {
    "appName": "AuraSlim Pro",
    "navWatch": "Smartwatch",
    "projectedWeight4w": "Peso previsto (4 sett.)",
    "projectedWeightSubtitle": "Proiezione con regressione lineare",
    "weeklyTrendRate": "Ritmo settimanale",
    "projectedGoalDate": "Obiettivo stimato entro il",
    "projectedBadge": "+4 sett. Proiezione",
    "proPlanBadge": "AuraSlim VIP Pro",
    "paymentPrice": "19,99 € / mese",
    "payApplePay": "Paga con Apple Pay",
    "cardExpiry": "Scadenza",
    "cardCvc": "CVC",
    "voiceInputTitle": "Inserimento vocale misurazioni",
    "voiceInputListening": "Ascolto... Parla ora",
    "voiceInputHint": "Dici ad es.: '72,5 kg, vita 80, 2,5 litri di acqua'",
    "voiceInputStop": "Ferma",
    "voiceMicTooltip": "Inserisci con microfono",
    "voiceNotSupported": "Riconoscimento vocale non supportato in questo browser.",
    "nutritionPdfBannerTitle": "Bilancio Nutrizionale Personale",
    "nutritionPdfBannerBadge": "PDF DISPONIBILE",
    "nutritionPdfBannerDesc": "Scarica il tuo bilancio nutrizionale completo con macronutrienti per il tuo dietista.",
    "nutritionPdfBannerBtn": "Genera bilancio (PDF)",
    "periodsOfDayTitle": "Momenti della giornata",
    "clickToChooseFoodHint": "Clicca su + per scegliere i tuoi alimenti",
    "periodBreakfast": "Colazione",
    "periodLunch": "Pranzo",
    "periodDinner": "Cena",
    "periodSnack": "Spuntino",
    "chooseBtn": "Scegli",
    "keyOptionScanBadge": "OPZIONE CONSIGLIATA",
    "scanPlateDescription": "Scansiona il piatto con l'IA o aggiungi alimenti per momento della giornata.",
    "targetedMealLabel": "Pasto target:",
    "takePlatePhotoBtn": "Fotografa il piatto",
    "directBadge": "DIRETTO",
    "deviceCameraDesc": "Fotocamera live del dispositivo per il riconoscimento istantaneo di calorie e nutrienti.",
    "galleryPhotosBtn": "Galleria foto",
    "importExistingPhotoDesc": "Importa foto esistente del piatto dalla galleria.",
    "foodIdeasFor": "Idee alimentari per:",
    "searchFoodPlaceholder": "Cerca un alimento...",
    "todayLoggedMealsTitle": "Pasti registrati oggi",
    "totalAlimentsSuffix": "in totale",
    "noMealsLoggedToday": "Nessun pasto registrato oggi. Clicca sul pulsante '+' di un pasto per iniziare.",
    "mealsHistoryTitle": "Cronologia pasti",
    "noMealsHistory": "Nessun pasto registrato.",
    "photoEvolutionTitle": "Evoluzione in foto",
    "photoEvolutionSubtitle": "Giorno 1 e foto di pesata salvate su questo dispositivo.",
    "addPhotoBtn": "Aggiungi foto",
    "generateVideoBtn": "Genera il mio video",
    "galleryCountLabel": "foto",
    "compareBeforeAfterTitle": "Confronto Prima / Dopo",
    "dragCenterToCompareHint": "Scorri il cursore centrale per confrontare la tua silhouette prima e dopo.",
    "photoBeforeLabel": "Foto Prima",
    "photoAfterLabel": "Foto Dopo",
    "badgeAvant": "PRIMA",
    "badgeApres": "DOPO",
    "dayOneLabel": "Giorno 1",
    "weekAbbrev": "Sett.",
    "freeBadge": "Gratuito",
    "premiumBadge": "Premium",
    "disclaimerFooter": "AuraSlim · Monitoraggio personale: i risultati e le analisi IA rimangono stime.",
    "offersBtn": "Offerte",
    "newPhotoModalTitle": "Aggiungi una foto corporea",
    "newPhotoModalSubtitle": "Salva le foto della tua evoluzione nella tua galleria locale privata.",
    "photoAngleFace": "Frontale (obbligatoria)",
    "photoAngleProfile": "Profilo (facoltativa)",
    "photoAngleBackLabel": "Schiena (facoltativa)",
    "notesOptionalPlaceholder": "Sensazioni, misure, abbigliamento...",
    "cancelBtn": "Annulla",
    "saveBtn": "Salva foto",
    "unlimitedScanMealOption": "Scansione piatti con IA illimitata",
    "activateScanOption": "Attiva scansione IA",
    "plateRecognizedSuccess": "Piatto riconosciuto con successo",
    "estimatedPortion": "Porzione stimata",
    "saveMealToLog": "Salva pasto nel mio diario",
    "recognizedFoodsAi": "Alimenti riconosciuti (stima IA)",
    "listenFoods": "Ascolta alimenti",
    "photoFitCover": "Riempi",
    "photoFitContain": "Adatta",
    "photoWaitingSecond": "In attesa della seconda foto",
    "photoWaitingSecondDesc": "Aggiungi almeno una seconda foto di pesata per confrontare il tuo prima e dopo.",
    "photoTakeSecondBtn": "Scatta 2ª foto",
    "photoFromGallery": "Dalla galleria",
    "photoFromCamera": "Con fotocamera",
    "photoFreeLimitNotice": "Due foto aggiuntive di pesata o evoluzione incluse dopo il Giorno 1.",
    "photoDragHintBottom": "Trascina orizzontalmente per scoprire l'evoluzione",
    "photoDayOne": "Foto Giorno 1",
    "accountSettingsTitle": "Impostazioni e privacy",
    "accountMyPlan": "Il mio piano",
    "accountPlanFree": "Gratuito",
    "accountPlanDesc": "Modalità gratuita: 1 foto dopo il Giorno 1 e 1 scansione del piatto.",
    "accountViewOffersBtn": "Vedi offerte Premium",
    "accountTrialTitle": "Codice di prova fornito da AuraSlim",
    "accountTrialPlaceholder": "Inserisci il codice di prova",
    "accountTrialBtn": "Attiva prova",
    "accountTrialSuccess": "Accesso di prova attivato con successo!",
    "accountShareAdminTitle": "Condividi con amministratore (facoltativo)",
    "accountShareAdminDesc": "Se attivato, i tuoi dati di peso e nutrizione saranno sincronizzati per il tuo percorso.",
    "accountShareAdminConsent": "Autorizza il monitoraggio",
    "accountLangTitle": "Lingua e valuta",
    "accountLangDesc": "Lingua dell'app e valuta di fatturazione, modificabili in qualsiasi momento.",
    "accountAppLanguage": "Lingua dell'applicazione",
    "accountCurrency": "Valuta desiderata",
    "accountStripeNotice": "Prezzo e valuta sono confermati sulla schermata protetta di Stripe.",
    "accountPatternTitle": "Blocco sequenza locale",
    "accountPatternDesc": "Sequenza segreta per proteggere lo schermo su questo dispositivo.",
    "accountPatternCreateBtn": "Crea o modifica sequenza",
    "accountPatternLockBtn": "Blocca ora",
    "accountPatternDisableBtn": "Disattiva sequenza",
    "accountWatchTitle": "Orologio e attività",
    "accountDataTitle": "I miei dati",
    "accountDataDesc": "Foto, pesate e pasti rimangono memorizzati su questo dispositivo.",
    "accountExportBtn": "Esporta i miei dati (JSON)",
    "accountPdfReportBtn": "Vedi bilancio PDF",
    "accountDeleteDataBtn": "Cancella i miei dati",
    "accountDeleteDataConfirm": "Eliminare definitivamente tutti i dati locali AuraSlim su questo dispositivo?",
    "pdfReportTitle": "Relazione di monitoraggio della salute",
    "pdfReportSubtitle": "Sintesi clinica e nutrizionale per il tuo specialista",
    "pdfStart": "Iniziale",
    "pdfLatest": "Ultimo",
    "pdfChange": "Variazione",
    "pdfGoal": "Obiettivo",
    "pdfWeightTrend": "Evoluzione delle pesate",
    "pdfMeasurements": "Misure e obiettivi",
    "pdfWeightLog": "Registro delle pesate",
    "pdfMealLog": "Registro dei pasti",
    "pdfDownloadBtn": "Scarica relazione PDF",
    "pdfPreparing": "Preparazione del report PDF…",
    "notificationAllowed": "Notifiche attivate con successo",
    "notificationDenied": "Notifiche bloccate nel browser.",
    "notificationUnsupported": "Notifiche non supportate su questo dispositivo.",
    "justNow": "proprio ora",
    "reminderNotificationBody": "È il momento della tua pesata o idratazione AuraSlim!",
    "frequencyDaily": "Giornaliero",
    "frequencyHourly": "Ogni ora",
    "frequencyWeekly": "Settimanale (domenica)",
    "waterTrackerTitle": "Monitoraggio idratazione",
    "waterTargetLabel": "Obiettivo idrico giornaliero:",
    "waterGoalReached": "Obiettivo acqua raggiunto! Idratazione ideale 💧",
    "waterResetDay": "Reimposta giornata",
    "waterNoGlassesToday": "Nessun bicchiere registrato oggi. Clicca su un bicchiere per registrare idratazione.",
    "waterDeleteEntry": "Elimina questa voce",
    "dailyHydrationGoalTitle": "Obiettivo idrico quotidiano",
    "dailyHydrationGoalDesc": "Imposta la quantità di acqua giornaliera raccomandata.",
    "litersPerDayUnit": "L/giorno",
    "waterLogsTodayTitle": "Assunzioni di oggi",
    "waterEditGoalTitle": "Modifica obiettivo",
    "sinceStart": "Dall'inizio:",
    "weekAbbrevShort": "Sett.",
    "remainingLabel": "Rimanente:",
    "globalProgress": "Progresso globale:",
    "weeklyStartWeightLabel": "Inizio settimana:",
    "weeklyTargetLabel": "Obiettivo settimana:",
    "weeklyProgressAchievedTitle": "Obiettivo settimanale raggiunto!",
    "weeklyRemainingLabel": "Rimanente questa settimana:",
    "milestoneStart": "Inizio",
    "milestoneCurrent": "Attuale",
    "milestoneSundayTarget": "Meta domenica",
    "daysUntilSundayLabel": "giorni a domenica",
    "projected4wTitle": "Proiezione a 4 settimane",
    "projected4wSubtitle": "Calcolata sul ritmo regolare delle tue ultime pesate",
    "paceLabel": "Ritmo settimanale:",
    "weekUnit": "sett.",
    "projectedWeight28d": "Peso previsto tra 28 giorni:",
    "estimatedGoalDateLabel": "Obiettivo previsto il:",
    "daysUnit": "giorni",
    "goalAchievedMaintenance": "Obiettivo raggiunto! Fase di mantenimento",
    "maintainingPace": "Mantenimento del ritmo costante",
    "fitR2Label": "Affidabilità del modello (R²):",
    "weightHistoryTrendTitle": "Tendenza e dinamica del peso",
    "weightChartSubtitle": "Curva reale delle pesate e regressione lineare predittiva",
    "chartReadingDirection": "Grafico cronologico (sinistra: inizio · destra: recente)",
    "goalLabel": "Obiettivo:",
    "measuredWeightLegend": "Pesate registrate",
    "projection4wLegend": "Proiezione a 4 settimane",
    "goalLegend": "Obiettivo fissato",
    "latestWeighInLabel": "Ultima registrazione:",
    "todayLabel": "Oggi",
    "weighInsLoggedCount": "pesate registrate",
    "bodyFatAbbrev": "G.C.",
    "logWeightSubtitle": "Registra la pesata con foto facoltativa della bilancia e note",
    "voiceListeningBadge": "Ascolto con il microfono...",
    "dictateBtn": "Ditta",
    "voiceStopDictation": "Ferma dettatura",
    "voiceStartDictation": "Detta a voce",
    "bodyWeightInputLabel": "Peso corporeo (kg) *",
    "scalePhotoOrSilhouette": "Foto del display della bilancia",
    "optionalBadge": "opzionale",
    "photoSavedBadge": "Foto pronta",
    "takeScalePhotoBtn": "Fotografa bilancia",
    "waistInputLabel": "Circonferenza vita (cm)",
    "dictateWaist": "Detta vita",
    "moodGreat": "Ottimo",
    "moodGood": "Bene",
    "moodNeutral": "Normale",
    "moodStruggling": "Difficile",
    "notesLabel": "Note o contesto",
    "dictateNotes": "Detta note",
    "notesPlaceholder": "Digiuno, post-allenamento, energia...",
    "twoPhotosFreeUsedNotice": "Foto gratuite esaurite. Attiva Pro per foto e scansioni illimitate.",
    "videoStepDayOne": "Giorno 1",
    "videoOverlayTitle": "AuraSlim • Evoluzione",
    "videoOverlaySubtitle": "Trasformazione fisica in foto",
    "videoInitialWeightLabel": "Iniziale",
    "videoVariationLabel": "Variazione",
    "videoEvolutionLabel": "Evoluzione",
    "videoModalTitle": "Video di progresso della trasformazione",
    "videoModalSubtitle": "Genera un video fluido della tua trasformazione prima / dopo.",
    "videoGeneratingText": "Rendering del video HD in corso…",
    "downloadVideoBtn": "Scarica il mio video (MP4)",
    "shareVideoBtn": "Condividi video",
    "socialMediaHeading": "Condividi sui social network:",
    "copyLinkBtn": "Copia link del progresso",
    "linkCopiedBadge": "Link copiato!",
    "shareMoreBtn": "Condividi con altre app",
    "videoShareTip": "Consiglio: scarica il file MP4 per pubblicarlo nelle tue storie o inviarlo al tuo coach.",
    "videoTimelineTitle": "Sequenza temporale del video:",
    "videoPrivacyNotice": "Le tue foto vengono elaborate esclusivamente in questo browser. Nessun video viene archiviato nel cloud senza il tuo consenso.",
    "videoLoadingPhoto": "Caricamento foto…",
    "videoCannotLoadPhotoError": "Impossibile caricare la foto per il video.",
    "videoRecorderNotSupportedError": "MediaRecorder non supportato in questo browser.",
    "videoEmptyError": "Non ci sono abbastanza foto per creare il video.",
    "videoRecordingError": "Errore durante la registrazione del video.",
    "calorieScanDisclaimer": "L'analisi fotografica tramite IA fornisce stime nutrizionali indicative.",
    "retryWithThisPhoto": "Riprova con questa foto",
    "unlockScanPricing": "Sblocca scansioni illimitate",
    "aiIdentifyingIngredients": "L'IA sta identificando gli ingredienti…",
    "mealIdeasDisclaimer": "Oltre dieci idee per pasto; porzioni e calorie sono indicative. Adatta con un professionista.",
    "indicativePortionLabel": "Porzione indicativa",
    "forQuantityLabel": "per",
    "addToMealTitle": "Aggiungi al pasto",
    "photoOfLoggedMeal": "Foto del piatto registrato",
    "photoDishForMeal": "Fotografa il piatto",
    "centerPlateSubtitle": "Posiziona il piatto al centro per una stima accurata dei macronutrienti",
    "foodPhotoIllustrativeDesc": "Foto reale illustrativa della categoria · Porzione indicativa.",
    "photoSourceCommons": "Fonte dell'immagine (Wikimedia Commons, CC0)",
    "removeFoodItem": "Rimuovi questo alimento",
    "paymentTariffsDesc": "Tariffe mensili in euro. Verifica l'importo visualizzato su Stripe.",
    "paymentStripeTestNotice": "Modalità di test Stripe: usa una carta di test. Nessun addebito reale.",
    "paymentPayOnStripe": "Paga su Stripe:",
    "paymentPreparingLink": "Preparazione del link protetto…",
    "paymentCheckoutDisclaimer": "Il pagamento si apre su una pagina sicura di Stripe. AuraSlim non conserva dati della carta.",
    "patternScreenLockDesc": "Blocco schermo locale. Salva e fai il backup dei tuoi dati nelle impostazioni.",
    "loadingLocalData": "Caricamento dei dati locali…",
    "startingWeightLabel": "Peso iniziale",
    "dayOnePhotoLabel": "Foto Giorno 1",
    "checkingSubscription": "Verifica abbonamento…",
    "remainingPhotosCount": "rimanenti",
    "frontPhotoRequiredError": "È richiesta una foto frontale per il confronto prima e dopo.",
    "macroCalories": "Calorie",
    "nutritionReportTitle": "Bilancio Nutrizionale Personale",
    "pdfAvailableBadge": "PDF DISPONIBILE",
    "nutritionReportSubtitle": "Consulta le tue misurazioni e i pasti salvati. Le stime non sostituiscono il parere medico.",
    "generateNutritionReportPdf": "Genera Bilancio Nutrizionale (PDF)",
    "addAnalyzedPlateToLog": "Salva questo piatto nel mio diario",
    "portionLabel": "Porzione",
    "scanAiBadge": "Scansione IA",
    "analyzedDishAlt": "Piatto analizzato",
    "ingredientsUncertainNotice": "I dettagli di ogni ingrediente sono orientativi; è stato stimato l'intero pasto.",
    "plateScanDisclaimer": "Quantità e calorie derivate da un'immagine rimangono approssimative.",
    "macroTargetLabel": "Target",
    "foodsPlural": "alimenti",
    "foodSingular": "alimento",
    "cameraHttpsRequired": "La fotocamera live richiede HTTPS e permessi del browser. Prova la fotocamera del telefono o seleziona una foto.",
    "cameraUnavailableError": "Impossibile attivare il flusso video live. Usa il pulsante diretto o la galleria.",
    "cameraActivating": "Attivazione della fotocamera...",
    "cameraDirectAccessTitle": "Accesso diretto alla fotocamera disponibile",
    "cameraDirectAccessDesc": "Consenti la fotocamera nel browser o usa lo scatto del tuo dispositivo.",
    "cameraOpenDirectDevice": "📸 Apri fotocamera del dispositivo",
    "cameraRetryStream": "Riprova flusso",
    "cameraHowToAuthorize": "Come consentire la fotocamera nel browser?",
    "cameraHowToAuthorizeStepTitle": "Per consentire il flusso live:",
    "cameraHowToAuthorizeStep1": "1. Clicca sul lucchetto 🔒 a sinistra dell'indirizzo URL.",
    "cameraHowToAuthorizeStep2": "2. Imposta il permesso Fotocamera su Consenti.",
    "cameraHowToAuthorizeStep3": "3. Clicca su Riprova o ricarica la pagina.",
    "cameraTimerActive": "3s Attivo",
    "cameraTimer": "Timer",
    "cameraFacingBack": "Posteriore",
    "cameraFacingFront": "Anteriore",
    "cameraTriggerShutter": "Scatta",
    "cameraDirectNativeTitle": "Fotocamera diretta",
    "cameraDirectBadge": "Diretto",
    "dragSliderLabel": "Trascina",
    "nutritionMealsLoggedSummary": "{count} alimento/i registrato/i oggi. Obiettivo indicativo: {target} kcal.",
    "nutritionHydrationSummary": "Idratazione registrata su obiettivo di {goal} L.",
    "nutritionLatestWeightSummary": "Ultima pesata registrata: {date}.",
    "voiceMeasurementSaved": "Misura registrata:",
    "bmiUnderweight": "Sottopeso",
    "bmiNormal": "Normale / Ideale",
    "bmiOverweight": "Sovrappeso lieve",
    "bmiObese": "Obesità",
    "shareLostWeight": "Ho già perso {weight} kg!",
    "shareGainedWeight": "Ho guadagnato {weight} kg di massa muscolare!",
    "shareRegularTracking": "Progresso costante con la mia trasformazione corporea",
    "shareProgressPrefix": "La mia trasformazione fisica su AuraSlim",
    "shareProgressSuffix": "Segui la tua trasformazione",
    "clipboardInaccessible": "Appunti non accessibili su questo dispositivo.",
    "shareVideoTitle": "La mia evoluzione fisica su AuraSlim",
    "shareDirectUnavailable": "Condivisione diretta non disponibile. Usa WhatsApp, Viber o copia il link.",
    "shareFileUnavailable": "Condivisione file non disponibile su questo dispositivo. Usa WhatsApp o copia il link.",
    "patternConfirmedNotice": "Sequenza confermata. Ricorda di esportare i tuoi dati regolarmente.",
    "patternAccepted": "Sequenza accettata.",
    "patternLockoutMessage": "Troppi tentativi errati. Riprova tra 30 secondi.",
    "patternRegisteredSuccess": "Sequenza confermata e salvata su questo dispositivo.",
    "patternSecurityLockoutTitle": "Blocco di sicurezza",
    "patternLockoutCountdownNotice": "Tentativi massimi superati. Sblocco in:",
    "paymentPrepError": "Impossibile preparare il link Stripe. Apri AuraSlim dal suo server.",
    "nativeAppPaymentNotice": "Gli acquisti in-app vengono gestiti tramite lo store ufficiale dell'applicazione.",
    "accountWatchConnectDesc": "Associa un dispositivo Bluetooth compatibile per leggere batteria o frequenza cardiaca. Le notifiche compaiono nel browser.",
    "connectingStatus": "Connessione…",
    "accountWatchPairBtn": "Associa dispositivo Bluetooth",
    "disconnectBtn": "Disconnetti",
    "accountWatchTestBtn": "Prova un promemoria su questo dispositivo",
    "batteryLabel": "Batteria",
    "heartRateLabel": "Frequenza cardiaca"
}

with open("src/services/translations/it.ts", "w") as f:
    f.write("import type { TranslationDictionary } from '../i18n';\n\n")
    f.write("export const itTranslations: Partial<TranslationDictionary> = " + json.dumps(IT_MAPPINGS, indent=2, ensure_ascii=False) + ";\n")

print("Created src/services/translations/it.ts")
