#!/usr/bin/env python3
import json
import os

os.makedirs("src/services/translations", exist_ok=True)

DE_MAPPINGS = {
    "appName": "AuraSlim Pro",
    "navWatch": "Smartwatch",
    "projectedWeight4w": "Prognostiziertes Gewicht (4 Wo.)",
    "projectedWeightSubtitle": "Prognose mittels linearer Regression",
    "weeklyTrendRate": "Wöchentliches Tempo",
    "projectedGoalDate": "Ziel voraussichtlich erreicht am",
    "projectedBadge": "+4 Wo. Prognose",
    "proPlanBadge": "AuraSlim VIP Pro",
    "paymentPrice": "19,99 € / Monat",
    "payApplePay": "Mit Apple Pay zahlen",
    "cardExpiry": "Gültig bis",
    "cardCvc": "CVC",
    "voiceInputTitle": "Spracheingabe von Messwerten",
    "voiceInputListening": "Zuhören... Jetzt sprechen",
    "voiceInputHint": "Sagen Sie z. B.: '72,5 kg, Taille 80, 2,5 Liter Wasser'",
    "voiceInputStop": "Stopp",
    "voiceMicTooltip": "Mit Mikrofon eingeben",
    "voiceNotSupported": "Spracherkennung in diesem Browser nicht unterstützt.",
    "nutritionPdfBannerTitle": "Persönlicher Ernährungsbericht",
    "nutritionPdfBannerBadge": "PDF VERFÜGBAR",
    "nutritionPdfBannerDesc": "Laden Sie Ihre vollständige Ernährungsbilanz mit Makronährstoffen für Ihre Ernährungsberatung herunter.",
    "nutritionPdfBannerBtn": "Bericht erstellen (PDF)",
    "periodsOfDayTitle": "Tageszeiten",
    "clickToChooseFoodHint": "Klicken Sie auf +, um Ihre Lebensmittel auszuwählen",
    "periodBreakfast": "Frühstück",
    "periodLunch": "Mittagessen",
    "periodDinner": "Abendessen",
    "periodSnack": "Snack",
    "chooseBtn": "Auswählen",
    "keyOptionScanBadge": "EMPFOHLENE OPTION",
    "scanPlateDescription": "Scannen Sie Ihren Teller mit KI oder fügen Sie Mahlzeiten manuell hinzu.",
    "targetedMealLabel": "Ziel-Mahlzeit:",
    "takePlatePhotoBtn": "Teller fotografieren",
    "directBadge": "DIREKT",
    "deviceCameraDesc": "Live-Kamera des Geräts zur sofortigen Nährwert- und Kalorienerkennung.",
    "galleryPhotosBtn": "Fotogalerie",
    "importExistingPhotoDesc": "Vorhandenes Foto Ihres Tellers aus der Galerie importieren.",
    "foodIdeasFor": "Lebensmittelideen für:",
    "searchFoodPlaceholder": "Lebensmittel suchen...",
    "todayLoggedMealsTitle": "Heute erfasste Mahlzeiten",
    "totalAlimentsSuffix": "insgesamt",
    "noMealsLoggedToday": "Heute noch keine Mahlzeiten erfasst. Klicken Sie auf '+' bei einer Mahlzeit, um zu beginnen.",
    "mealsHistoryTitle": "Mahlzeiten-Verlauf",
    "noMealsHistory": "Keine Mahlzeiten erfasst.",
    "photoEvolutionTitle": "Entwicklung in Fotos",
    "photoEvolutionSubtitle": "Tag 1 und Wiegefotos auf diesem Gerät gespeichert.",
    "addPhotoBtn": "Foto hinzufügen",
    "generateVideoBtn": "Mein Video erstellen",
    "galleryCountLabel": "Fotos",
    "compareBeforeAfterTitle": "Vorher / Nachher Vergleich",
    "dragCenterToCompareHint": "Schieben Sie den mittleren Regler, um Vorher und Nachher zu vergleichen.",
    "photoBeforeLabel": "Vorher",
    "photoAfterLabel": "Nachher",
    "badgeAvant": "VORHER",
    "badgeApres": "NACHHER",
    "dayOneLabel": "Tag 1",
    "weekAbbrev": "Woche",
    "freeBadge": "Kostenlos",
    "premiumBadge": "Premium",
    "disclaimerFooter": "AuraSlim · Persönliches Tracking: Ergebnisse und KI-Analysen sind Schätzwerte.",
    "offersBtn": "Angebote",
    "newPhotoModalTitle": "Körperfoto hinzufügen",
    "newPhotoModalSubtitle": "Speichern Sie Ihre Fortschrittsfotos in Ihrer privaten lokalen Galerie.",
    "photoAngleFace": "Frontalansicht (erforderlich)",
    "photoAngleProfile": "Seitenansicht (optional)",
    "photoAngleBackLabel": "Rückenansicht (optional)",
    "notesOptionalPlaceholder": "Gefühl, Maße, Kleidung...",
    "cancelBtn": "Abbrechen",
    "saveBtn": "Foto speichern",
    "unlimitedScanMealOption": "Unbegrenzter KI-Mahlzeitenscan",
    "activateScanOption": "KI-Scan aktivieren",
    "plateRecognizedSuccess": "Gericht erfolgreich erkannt",
    "estimatedPortion": "Geschätzte Portion",
    "saveMealToLog": "In mein Tagebuch eintragen",
    "recognizedFoodsAi": "Erkannte Lebensmittel (KI-Schätzung)",
    "listenFoods": "Lebensmittel vorlesen",
    "photoFitCover": "Füllen",
    "photoFitContain": "Einpassen",
    "photoWaitingSecond": "Warte auf zweites Foto",
    "photoWaitingSecondDesc": "Fügen Sie mindestens ein zweites Wiegefoto hinzu, um Vorher und Nachher zu vergleichen.",
    "photoTakeSecondBtn": "2. Foto aufnehmen",
    "photoFromGallery": "Aus Galerie",
    "photoFromCamera": "Mit Kamera",
    "photoFreeLimitNotice": "Zwei zusätzliche Wiege- oder Fortschrittsfotos nach Tag 1 enthalten.",
    "photoDragHintBottom": "Schieberegler horizontal bewegen, um den Fortschritt zu enthüllen",
    "photoDayOne": "Foto Tag 1",
    "accountSettingsTitle": "Einstellungen & Datenschutz",
    "accountMyPlan": "Mein Tarif",
    "accountPlanFree": "Kostenlos",
    "accountPlanDesc": "Kostenloser Modus: 1 Foto nach Tag 1 und 1 Tellerscan.",
    "accountViewOffersBtn": "Premium-Angebote anzeigen",
    "accountTrialTitle": "Testcode von AuraSlim",
    "accountTrialPlaceholder": "Testcode eingeben",
    "accountTrialBtn": "Testversion aktivieren",
    "accountTrialSuccess": "Testzugang erfolgreich aktiviert!",
    "accountShareAdminTitle": "Mit Administrator teilen (optional)",
    "accountShareAdminDesc": "Wenn aktiviert, werden Ihre Daten zur Betreuung mit dem Server synchronisiert.",
    "accountShareAdminConsent": "Betreuung erlauben",
    "accountLangTitle": "Sprache & Währung",
    "accountLangDesc": "App-Sprache und Abrechnungswährung jederzeit anpassbar.",
    "accountAppLanguage": "App-Sprache",
    "accountCurrency": "Wunschwährung",
    "accountStripeNotice": "Preis und Währung werden auf der sicheren Stripe-Seite bestätigt.",
    "accountPatternTitle": "Lokale Mustersperre",
    "accountPatternDesc": "Geheimes Wischmuster zum Schutz des Bildschirms auf diesem Gerät.",
    "accountPatternCreateBtn": "Muster erstellen / ändern",
    "accountPatternLockBtn": "Jetzt sperren",
    "accountPatternDisableBtn": "Muster deaktivieren",
    "accountWatchTitle": "Smartwatch & Aktivität",
    "accountDataTitle": "Meine Daten",
    "accountDataDesc": "Fotos, Wiegungen und Mahlzeiten verbleiben auf diesem Gerät.",
    "accountExportBtn": "Meine Daten exportieren (JSON)",
    "accountPdfReportBtn": "PDF-Bericht anzeigen",
    "accountDeleteDataBtn": "Meine Daten löschen",
    "accountDeleteDataConfirm": "Alle lokalen AuraSlim-Daten auf diesem Gerät endgültig löschen?",
    "pdfReportTitle": "Gesundheits- & Fortschrittsbericht",
    "pdfReportSubtitle": "Klinische Zusammenfassung für Ihre Ernährungsfachkraft",
    "pdfStart": "Start",
    "pdfLatest": "Aktuell",
    "pdfChange": "Veränderung",
    "pdfGoal": "Zielgewicht",
    "pdfWeightTrend": "Gewichtsverlauf",
    "pdfMeasurements": "Körpermaße & Ziele",
    "pdfWeightLog": "Wiege-Protokoll",
    "pdfMealLog": "Ernährungs-Protokoll",
    "pdfDownloadBtn": "PDF-Bericht herunterladen",
    "pdfPreparing": "PDF-Bericht wird vorbereitet…",
    "notificationAllowed": "Benachrichtigungen erfolgreich aktiviert",
    "notificationDenied": "Benachrichtigungen im Browser blockiert.",
    "notificationUnsupported": "Benachrichtigungen auf diesem Gerät nicht unterstützt.",
    "justNow": "gerade eben",
    "reminderNotificationBody": "Zeit für Ihr AuraSlim-Wiegen oder Ihre Hydratation!",
    "frequencyDaily": "Täglich",
    "frequencyHourly": "Stündlich",
    "frequencyWeekly": "Wöchentlich (Sonntag)",
    "waterTrackerTitle": "Flüssigkeitstracker",
    "waterTargetLabel": "Tagesziel Wasser:",
    "waterGoalReached": "Wasserziel erreicht! Perfekt hydriert 💧",
    "waterResetDay": "Tag zurücksetzen",
    "waterNoGlassesToday": "Heute noch kein Wasser erfasst. Klicken Sie auf ein Glas, um Wasser hinzuzufügen.",
    "waterDeleteEntry": "Diesen Eintrag löschen",
    "dailyHydrationGoalTitle": "Tägliches Wasserziel",
    "dailyHydrationGoalDesc": "Passen Sie Ihr empfohlenes tägliches Wasserziel an.",
    "litersPerDayUnit": "L/Tag",
    "waterLogsTodayTitle": "Heutige Einträge",
    "waterEditGoalTitle": "Ziel anpassen",
    "sinceStart": "Seit Beginn:",
    "weekAbbrevShort": "Woche",
    "remainingLabel": "Verbleibend:",
    "globalProgress": "Gesamtfortschritt:",
    "weeklyStartWeightLabel": "Wochenbeginn:",
    "weeklyTargetLabel": "Wochenziel:",
    "weeklyProgressAchievedTitle": "Wochenziel erreicht!",
    "weeklyRemainingLabel": "Noch diese Woche:",
    "milestoneStart": "Start",
    "milestoneCurrent": "Aktuell",
    "milestoneSundayTarget": "Sonntagsziel",
    "daysUntilSundayLabel": "Tage bis Sonntag",
    "projected4wTitle": "4-Wochen-Prognose",
    "projected4wSubtitle": "Berechnet auf Basis Ihres aktuellen Wiegerythmus",
    "paceLabel": "Wöchentliche Rate:",
    "weekUnit": "Wo.",
    "projectedWeight28d": "Gewicht in 28 Tagen:",
    "estimatedGoalDateLabel": "Ziel erreicht ca. am:",
    "daysUnit": "Tage",
    "goalAchievedMaintenance": "Ziel erreicht! Haltephase aktiv",
    "maintainingPace": "Gleichmäßiges Tempo beibehalten",
    "fitR2Label": "Modellzuverlässigkeit (R²):",
    "weightHistoryTrendTitle": "Gewichtstrend & Dynamik",
    "weightChartSubtitle": "Echte Wiegungen und prädiktive lineare Regression",
    "chartReadingDirection": "Chronologischer Verlauf (links: Beginn · rechts: aktuell)",
    "goalLabel": "Ziel:",
    "measuredWeightLegend": "Gemessene Wiegungen",
    "projection4wLegend": "4-Wochen-Prognose",
    "goalLegend": "Zielgewicht",
    "latestWeighInLabel": "Letzte Messung:",
    "todayLabel": "Heute",
    "weighInsLoggedCount": "Wiegungen erfasst",
    "bodyFatAbbrev": "KFA",
    "logWeightSubtitle": "Speichern Sie Ihr Gewicht mit Notizen und optionalem Foto",
    "voiceListeningBadge": "Mikrofon hört zu...",
    "dictateBtn": "Diktieren",
    "voiceStopDictation": "Diktat stoppen",
    "voiceStartDictation": "Per Sprache eingeben",
    "bodyWeightInputLabel": "Körpergewicht (kg) *",
    "scalePhotoOrSilhouette": "Foto der Waagenanzeige",
    "optionalBadge": "optional",
    "photoSavedBadge": "Foto bereit",
    "takeScalePhotoBtn": "Waage fotografieren",
    "waistInputLabel": "Taillenumfang (cm)",
    "dictateWaist": "Taille diktieren",
    "moodGreat": "Großartig",
    "moodGood": "Gut",
    "moodNeutral": "Normal",
    "moodStruggling": "Schwierig",
    "notesLabel": "Notizen oder Kontext",
    "dictateNotes": "Notizen diktieren",
    "notesPlaceholder": "Fasten, nach dem Sport, Energie...",
    "twoPhotosFreeUsedNotice": "Freie Fotos aufgebraucht. Aktivieren Sie Pro für unbegrenzte Fotos und Scans.",
    "videoStepDayOne": "Tag 1",
    "videoOverlayTitle": "AuraSlim • Fortschritt",
    "videoOverlaySubtitle": "Körperliche Veränderung in Fotos",
    "videoInitialWeightLabel": "Start",
    "videoVariationLabel": "Veränderung",
    "videoEvolutionLabel": "Entwicklung",
    "videoModalTitle": "Fortschrittsvideo Ihrer Transformation",
    "videoModalSubtitle": "Erstellen Sie ein flüssiges Video Ihrer Vorher-Nachher-Veränderung.",
    "videoGeneratingText": "HD-Video wird gerendert…",
    "downloadVideoBtn": "Mein Video herunterladen (MP4)",
    "shareVideoBtn": "Video teilen",
    "socialMediaHeading": "Auf sozialen Netzwerken teilen:",
    "copyLinkBtn": "Fortschrittslink kopieren",
    "linkCopiedBadge": "Link kopiert!",
    "shareMoreBtn": "Mit anderen Apps teilen",
    "videoShareTip": "Tipp: MP4-Datei herunterladen, um sie in Storys zu posten oder an Ihren Trainer zu senden.",
    "videoTimelineTitle": "Zeitstrahl des Videos:",
    "videoPrivacyNotice": "Ihre Fotos werden ausschließlich in diesem Browser verarbeitet. Kein Video wird ohne Ihre Zustimmung in der Cloud gespeichert.",
    "videoLoadingPhoto": "Foto wird geladen…",
    "videoCannotLoadPhotoError": "Foto konnte für das Video nicht geladen werden.",
    "videoRecorderNotSupportedError": "MediaRecorder wird von diesem Browser nicht unterstützt.",
    "videoEmptyError": "Nicht genügend Fotos vorhanden, um ein Video zu erstellen.",
    "videoRecordingError": "Fehler bei der Videoaufzeichnung.",
    "calorieScanDisclaimer": "Die KI-Fotoanalyse liefert ernährungswissenschaftliche Richtwerte.",
    "retryWithThisPhoto": "Mit diesem Foto wiederholen",
    "unlockScanPricing": "Unbegrenztes Scannen freischalten",
    "aiIdentifyingIngredients": "KI erkennt Zutaten…",
    "mealIdeasDisclaimer": "Über zehn Mahlzeiten-Ideen; Mengenangaben und Kalorien sind Richtwerte.",
    "indicativePortionLabel": "Richtportion",
    "forQuantityLabel": "für",
    "addToMealTitle": "Zur Mahlzeit hinzufügen",
    "photoOfLoggedMeal": "Foto der erfassten Mahlzeit",
    "photoDishForMeal": "Gericht fotografieren",
    "centerPlateSubtitle": "Platzieren Sie den Teller in der Mitte für eine genaue Nährwertanalyse",
    "foodPhotoIllustrativeDesc": "Illustratives Echtfoto der Kategorie · Richtportion.",
    "photoSourceCommons": "Bildquelle (Wikimedia Commons, CC0)",
    "removeFoodItem": "Dieses Lebensmittel entfernen",
    "paymentTariffsDesc": "Monatliche Tarife in Euro. Prüfen Sie den bei Stripe angezeigten Betrag.",
    "paymentStripeTestNotice": "Stripe-Testmodus: Verwenden Sie eine Testkarte. Es wird kein echtes Geld abgebucht.",
    "paymentPayOnStripe": "Auf Stripe zahlen:",
    "paymentPreparingLink": "Sicherer Link wird vorbereitet…",
    "paymentCheckoutDisclaimer": "Der Bezahlvorgang öffnet sich auf der sicheren Stripe-Seite. AuraSlim speichert keine Kartendaten.",
    "patternScreenLockDesc": "Lokale Bildschirmsperre. Sichern Sie Ihre Daten in den Einstellungen.",
    "loadingLocalData": "Lokale Daten werden geladen…",
    "startingWeightLabel": "Ausgangsgewicht",
    "dayOnePhotoLabel": "Foto Tag 1",
    "checkingSubscription": "Abonnement wird geprüft…",
    "remainingPhotosCount": "verbleibend",
    "frontPhotoRequiredError": "Ein Frontalfoto ist für den Vorher/Nachher-Vergleich erforderlich.",
    "macroCalories": "Kalorien",
    "nutritionReportTitle": "Persönlicher Ernährungsbericht",
    "pdfAvailableBadge": "PDF VERFÜGBAR",
    "nutritionReportSubtitle": "Überprüfen Sie Ihre Messwerte und Mahlzeiten. Schätzungen ersetzen keinen medizinischen Rat.",
    "generateNutritionReportPdf": "Ernährungsbericht generieren (PDF)",
    "addAnalyzedPlateToLog": "In mein Tagebuch eintragen",
    "portionLabel": "Portion",
    "scanAiBadge": "KI-Scan",
    "analyzedDishAlt": "Analysierter Teller",
    "ingredientsUncertainNotice": "Zutaten auf diesem Foto sind Schätzungen; die gesamte Mahlzeit wurde bewertet.",
    "plateScanDisclaimer": "Aus Bildern abgeleitete Mengen und Kalorien bleiben Näherungswerte.",
    "macroTargetLabel": "Ziel",
    "foodsPlural": "Lebensmittel",
    "foodSingular": "Lebensmittel",
    "cameraHttpsRequired": "Live-Kamera erfordert HTTPS und Browserberechtigung. Nutzen Sie die native Kamera oder wählen Sie ein Foto.",
    "cameraUnavailableError": "Live-Videostream konnte nicht gestartet werden. Nutzen Sie den Direkt-Button oder die Galerie.",
    "cameraActivating": "Kamera wird aktiviert...",
    "cameraDirectAccessTitle": "Direkter Kamerazugriff verfügbar",
    "cameraDirectAccessDesc": "Erlauben Sie die Kamera im Browser oder nutzen Sie die native Kamera Ihres Geräts.",
    "cameraOpenDirectDevice": "📸 Gerätekamera öffnen",
    "cameraRetryStream": "Stream wiederholen",
    "cameraHowToAuthorize": "Wie erlaube ich die Kamera im Browser?",
    "cameraHowToAuthorizeStepTitle": "Um den Live-Stream zu erlauben:",
    "cameraHowToAuthorizeStep1": "1. Klicken Sie links neben der URL-Adresse auf das Schloss 🔒.",
    "cameraHowToAuthorizeStep2": "2. Setzen Sie die Berechtigung für die Kamera auf Erlauben.",
    "cameraHowToAuthorizeStep3": "3. Klicken Sie auf Wiederholen oder laden Sie die Seite neu.",
    "cameraTimerActive": "3s Aktiv",
    "cameraTimer": "Selbstauslöser",
    "cameraFacingBack": "Hinten",
    "cameraFacingFront": "Vorne",
    "cameraTriggerShutter": "Auslösen",
    "cameraDirectNativeTitle": "Direktkamera",
    "cameraDirectBadge": "Direkt",
    "dragSliderLabel": "Schieben",
    "nutritionMealsLoggedSummary": "{count} Lebensmittel heute erfasst. Richtwert: {target} kcal.",
    "nutritionHydrationSummary": "Hydratation erfasst bezüglich {goal} L Tagesziel.",
    "nutritionLatestWeightSummary": "Letzte Wiegung erfasst: {date}.",
    "voiceMeasurementSaved": "Messwert gespeichert:",
    "bmiUnderweight": "Untergewicht",
    "bmiNormal": "Normal / Ideal",
    "bmiOverweight": "Leichtes Übergewicht",
    "bmiObese": "Adipositas",
    "shareLostWeight": "Ich habe bereits {weight} kg verloren!",
    "shareGainedWeight": "Ich habe {weight} kg Muskelmasse aufgebaut!",
    "shareRegularTracking": "Regelmäßiger Fortschritt bei meiner Transformation",
    "shareProgressPrefix": "Mein körperlicher Fortschritt auf AuraSlim",
    "shareProgressSuffix": "Verfolgen Sie Ihre Transformation",
    "clipboardInaccessible": "Zwischenablage auf diesem Gerät nicht verfügbar.",
    "shareVideoTitle": "Mein AuraSlim Transformationsvideo",
    "shareDirectUnavailable": "Direktes Teilen nicht verfügbar. Nutzen Sie WhatsApp, Viber oder den Link.",
    "shareFileUnavailable": "Dateifreigabe nicht verfügbar. Nutzen Sie WhatsApp oder kopieren Sie den Link.",
    "patternConfirmedNotice": "Muster bestätigt. Exportieren Sie regelmäßig Ihre Daten.",
    "patternAccepted": "Muster akzeptiert.",
    "patternLockoutMessage": "Zu viele Fehlversuche. Bitte in 30 Sekunden erneut versuchen.",
    "patternRegisteredSuccess": "Muster bestätigt und auf diesem Gerät gespeichert.",
    "patternSecurityLockoutTitle": "Sicherheitssperre",
    "patternLockoutCountdownNotice": "Maximale Versuche überschritten. Entsperrung in:",
    "paymentPrepError": "Stripe-Zahlungslink konnte nicht vorbereitet werden. Bitte öffnen Sie die App über den Server.",
    "nativeAppPaymentNotice": "In-App-Käufe werden über den jeweiligen App Store abgewickelt.",
    "accountWatchConnectDesc": "Kompatibles Bluetooth-Gerät verbinden, um Akku oder Puls auszulesen. Benachrichtigungen erscheinen im Browser.",
    "connectingStatus": "Verbinde…",
    "accountWatchPairBtn": "Bluetooth-Gerät koppeln",
    "disconnectBtn": "Trennen",
    "accountWatchTestBtn": "Erinnerung auf diesem Gerät testen",
    "batteryLabel": "Akku",
    "heartRateLabel": "Herzfrequenz"
}

with open("src/services/translations/de.ts", "w") as f:
    f.write("import type { TranslationDictionary } from '../i18n';\n\n")
    f.write("export const deTranslations: Partial<TranslationDictionary> = " + json.dumps(DE_MAPPINGS, indent=2, ensure_ascii=False) + ";\n")

print("Created src/services/translations/de.ts")
