import assert from 'node:assert/strict';
import express from 'express';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {mkdtemp,readFile,readdir,writeFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import type Stripe from 'stripe';
import {defaultProfile, STORAGE_KEYS, getStoredProfile} from '../src/services/storage.ts';
import {nutritionTarget,mealBudget} from '../src/services/nutritionTarget.ts';
import {personalProgram} from '../src/services/personalProgram.ts';
import {dailyGoals,closeDay,closedDays,DAY_END_KEY} from '../src/services/dailyGoals.ts';
import {checkoutDestination,parsePaymentReturn,cleanPaymentReturnUrl} from '../src/services/paymentReturn.ts';
import {checkoutSnapshot,encryptCheckoutSnapshot,decryptCheckoutSnapshot,parseRecoverySecret,restoreCheckoutSnapshot} from '../src/services/checkoutBackup.ts';
import {DailyGoalsCard} from '../src/components/DailyGoalsCard.tsx';
import {NutritionAdvice} from '../src/components/NutritionAdvice.tsx';
import {MealComposerTab} from '../src/components/MealComposerTab.tsx';
import {getTheme} from '../src/services/theme.ts';
import {getTranslation} from '../src/services/i18n.ts';
import {translationSources,createInterfaceTranslator} from '../src/services/interfaceTranslation.ts';
import {installPaymentRoutes} from '../server/payments.ts';
import {readCheckoutRecovery,saveCheckoutRecovery,newRecoveryToken,removeCheckoutRecovery} from '../server/checkoutRecovery.ts';

const values=new Map<string,string>();
const storage={getItem:(k:string)=>values.get(k) ?? null,setItem:(k:string,v:string)=>values.set(k,v),removeItem:(k:string)=>values.delete(k)} as unknown as Storage;
(globalThis as any).localStorage=storage;
const tmp=await mkdtemp(path.join(os.tmpdir(),'auraslim-v4-'));
process.env.AURASLIM_DATA_DIR=tmp;process.env.APP_URL='https://auraslim.example/';process.env.STRIPE_PRICE_SCAN_MEALS='price_meals';process.env.STRIPE_PRICE_PROGRESS_VIDEO='price_video';process.env.STRIPE_PRICE_COMPLETE_PACK='price_pack';
delete process.env.AURASLIM_BACKUP_BUCKET;
const theme=getTheme('male','light');
const profile={...defaultProfile,id:'user_v4',name:'Test privé',email:'test@example.invalid',isOnboardingCompleted:true,preferredLanguage:'fr',gender:'male' as const,metabolismSex:'male' as const,currentWeight:80,heightCm:180,age:35,targetWeight:70,dailyActivity:'seated' as const,exerciseMinutesPerWeek:0,waterGoalMode:'auto' as const};
const today='2026-10-06';
const meal=(n:number,date=today)=>({id:'meal_1',date,mealType:'lunch' as const,name:'Repas test',portion:'200g',calories:n,proteins:25,carbs:30,fats:10,scannedWithAI:false});
const water=[{id:'water1',date:today,time:'19:00',amountMl:2500}];
try {
 const seated=nutritionTarget(profile),moving=nutritionTarget({...profile,dailyActivity:'moving'}),sport=nutritionTarget({...profile,exerciseMinutesPerWeek:150});
 assert.equal(seated.bmr,1755,'Mifflin–St Jeor male reference');
 assert.equal(nutritionTarget({...profile,metabolismSex:'female'}).bmr,1589);
 assert.ok(moving.calories>seated.calories);assert.ok(sport.calories>seated.calories);assert.ok(moving.waterLiters>seated.waterLiters);
 const loss=seated.calories,maintain=nutritionTarget({...profile,weightGoal:'maintain'}).calories,gain=nutritionTarget({...profile,weightGoal:'gain'}).calories;
 assert.ok(loss<maintain&&maintain<gain);
 assert.equal(nutritionTarget({...profile,waterGoalMode:'manual',waterGoalLiters:1.75,dailyActivity:'physical'}).waterLiters,1.75);
 assert.equal(nutritionTarget({...profile,needsProfessionalPlan:true}).calories,profile.dailyCalorieTarget);
 assert.equal(nutritionTarget({...profile,targetWeight:45}).needsReview,true);
 assert.equal(nutritionTarget(profile,1600).bmr,1600);
 const program=personalProgram({...profile,exerciseMinutesPerWeek:150});assert.ok(Math.abs(program.proteinsG*4+program.carbsG*4+program.fatsG*9-program.calories)<=5);assert.equal(program.mealPlan.length,4);assert.equal(personalProgram({...profile,needsProfessionalPlan:true}).mealPlan.length,0);assert.match(personalProgram(profile).workoutPlan[0].frequency,/10 minutes/);assert.match(personalProgram({...profile,exerciseMinutesPerWeek:150}).workoutPlan[0].frequency,/150 minutes/);
 assert.equal(mealBudget(2000,'breakfast')+mealBudget(2000,'lunch')+mealBudget(2000,'snack')+mealBudget(2000,'dinner'),2000);
 assert.equal(dailyGoals(today,[meal(1896)],water,1745,2.5).excess,151);
 assert.equal(dailyGoals(today,[meal(1745),meal(800,'2026-10-05')],water,1745,2.5).success,true);
 assert.equal(dailyGoals(today,[meal(100)],water,1745,2.5).success,false,'Do not reward severe under-eating');
 assert.equal(dailyGoals(today,[meal(1745)],[],1745,2.5).success,false);
 closeDay(storage,profile.id,today,true);closeDay(storage,profile.id,today,true);assert.deepEqual(closedDays(storage,profile.id),[today]);
 assert.deepEqual(closedDays(storage,'another_user'),[]);
 storage.setItem(STORAGE_KEYS.WATER_LOGS,JSON.stringify(water));
 let html=renderToStaticMarkup(React.createElement(DailyGoalsCard,{profile,theme,meals:[meal(seated.calories+151)],date:today}));assert.match(html,/role="alert"/);assert.match(html,/151 kcal/);assert.doesNotMatch(html,/Bravo/);
 html=renderToStaticMarkup(React.createElement(DailyGoalsCard,{profile,theme,meals:[meal(seated.calories)],date:today}));assert.match(html,/Bravo/);
 html=renderToStaticMarkup(React.createElement(DailyGoalsCard,{profile:{...profile,needsProfessionalPlan:true},theme,meals:[meal(5000)],date:today}));assert.doesNotMatch(html,/role="alert"/);assert.match(html,/Objectif à valider/);assert.doesNotMatch(html,/Bravo/);
 closeDay(storage,profile.id,today,false);html=renderToStaticMarkup(React.createElement(DailyGoalsCard,{profile,theme,meals:[meal(seated.calories)],date:today}));assert.doesNotMatch(html,/Bravo/);assert.match(html,/Terminer ma journée/);
 html=renderToStaticMarkup(React.createElement(DailyGoalsCard,{profile,theme,meals:[meal(1896)],date:'2026-10-07'}));assert.match(html,/0 kcal/);assert.doesNotMatch(html,/Bravo/);
 for(const goal of ['lose','gain','maintain'] as const){html=renderToStaticMarkup(React.createElement(NutritionAdvice,{profile:{...profile,weightGoal:goal},theme,onEdit(){}}));assert.match(html,/programme nutrition et activité/);assert.match(html,goal==='lose'?/réduction modérée/:goal==='gain'?/300 kcal supplémentaires/:/maintien du poids/);}
 html=renderToStaticMarkup(React.createElement(MealComposerTab,{profile,nutritionEntries:[],theme,t:getTranslation('fr'),onAddNutrition(){},onDeleteNutrition(){}}));assert.match(html,/class="meal-periods"/);assert.equal((html.match(/role="tab"/g)||[]).length,4);assert.match(html,/Pause après-midi/);assert.match(html,/Repère pour ce repas/);
 const sources=translationSources();const required=['Votre journée habituelle, hors sport','Terminer ma journée','Mon activité et mes besoins quotidiens','Pause après-midi'];for(const text of required)assert.ok(Object.values(sources).includes(text),'Missing translation source: '+text);
 const over=Object.keys(sources).find(k=>sources[k].includes('Vous avez dépassé votre objectif quotidien de {slot_0}'));assert.ok(over);
 const translator=createInterfaceTranslator({...sources,[over!]:'🚨 تجاوزت هدفك اليومي بمقدار {slot_0} سعرة حرارية. حافظ على وجبات منتظمة.'});assert.equal(translator('🚨 Vous avez dépassé votre objectif quotidien de 151 kcal. Gardez des repas réguliers, sans sauter de repas pour compenser.'),'🚨 تجاوزت هدفك اليومي بمقدار 151 سعرة حرارية. حافظ على وجبات منتظمة.');
 assert.equal(checkoutDestination('scan_meals','photos'),'nutrition');assert.equal(checkoutDestination('progress_video','account'),'photos');assert.equal(checkoutDestination('complete_pack','compose'),'compose');
 const weights=[{id:'w1',date:today,weight:80,mood:'good' as const,photoUrl:'data:image/jpeg;base64,cGhvdG8='}],photos=[{id:'p1',date:today,weekNumber:0,angle:'front' as const,imageUrl:weights[0].photoUrl,weightAtTime:80}];
 storage.setItem(`auraslim_inbody_scans_${profile.id}`,JSON.stringify([{id:'i1',bmrKcal:1600}]));
 closeDay(storage,profile.id,today,true);
 storage.setItem('auraslim_verified_sessions',JSON.stringify(['cs_test_previous']));
 const snapshot=checkoutSnapshot(profile,weights,photos,[meal(1745)],[],storage);
 const encrypted=await encryptCheckoutSnapshot(snapshot);
 const token='a'.repeat(64),secret={token,key:encrypted.recoveryKey,session:'cs_test_v4'};
 assert.deepEqual(await decryptCheckoutSnapshot(encrypted.encrypted,secret),JSON.parse(JSON.stringify(snapshot)));
 await assert.rejects(decryptCheckoutSnapshot(encrypted.encrypted,{...secret,key:'b'.repeat(64)}));
 const modified={...encrypted.encrypted,cipher:(encrypted.encrypted.cipher[0]==='A'?'B':'A')+encrypted.encrypted.cipher.slice(1)};await assert.rejects(decryptCheckoutSnapshot(modified,secret));
 let client='a'.repeat(48),created:any;
 const prices={price_meals:{id:'price_meals',active:true,currency:'eur',unit_amount:399,recurring:{interval:'month'}},price_video:{id:'price_video',active:true,currency:'eur',unit_amount:399,recurring:{interval:'month'}},price_pack:{id:'price_pack',active:true,currency:'eur',unit_amount:699,recurring:{interval:'month'}}};
 let session:any={id:'cs_test_v4',client_reference_id:client,mode:'subscription',status:'complete',payment_status:'paid',subscription:'sub_v4',metadata:{plan:'scan_meals',return_tab:'nutrition'}};
 const stripe={prices:{retrieve:async(id:keyof typeof prices)=>prices[id]},checkout:{sessions:{create:async(options:any)=>{created=options;return {id:session.id,url:'https://checkout.stripe.com/c/pay/cs_test_v4'};},retrieve:async()=>session}},subscriptions:{retrieve:async()=>({id:'sub_v4',status:'active',items:{data:[{price:prices.price_meals}]}})}} as unknown as Stripe;
 const app=express();installPaymentRoutes(app,stripe,()=>client,()=>true);
 const request=async(method:'get'|'post',route:string,body:any={},query:any={},recoveryToken?:string)=>{const layer=(app as any)._router.stack.find((l:any)=>l.route?.methods[method]&&l.route.path.includes('/auraslim-api/'+route));assert.ok(layer);let status=200,data:any;const res={set(){return this;},status(n:number){status=n;return this;},json(v:any){data=v;return this;},cookie(_name:string,id:string){client=id;}};await layer.route.stack.at(-1).handle({body,query,protocol:'https',get:(header:string)=>header.toLowerCase()==='x-auraslim-recovery'?recoveryToken:header==='host'?'auraslim.example':undefined},res);return {status,data};};
 const body={plan:'scan_meals',currency:'EUR',returnTab:'compose',returnUrl:'https://auraslim.example/?theme=light',backup:encrypted.encrypted,recoveryKey:encrypted.recoveryKey,expectedPriceEur:3.99};
 const checkout=await request('post','checkout',body);assert.equal(checkout.status,200);assert.equal(checkout.data.returnTab,'nutrition');assert.equal(created.metadata.return_tab,'nutrition');
 const success=new URL(created.success_url.replace('{CHECKOUT_SESSION_ID}',session.id));assert.equal(success.searchParams.get('session_id'),session.id);assert.equal(success.searchParams.get('return_tab'),'nutrition');assert.equal(success.hash.length,148);
 const parsedSecret=parseRecoverySecret(success.hash,session.id)!;assert.equal(parsedSecret.token,checkout.data.recoveryToken);
 const cancel=new URL(created.cancel_url);assert.equal(cancel.searchParams.get('return_tab'),'compose');assert.ok(parseRecoverySecret(cancel.hash,null),'Cancellation also preserves records');
 assert.equal(parsePaymentReturn('?checkout=success&session_id=cs_test_v4&return_tab=photos&open_video=1')?.openVideo,true);
 assert.equal(cleanPaymentReturnUrl(success.href),'https://auraslim.example/?theme=light');
 const disk=await readFile(path.join(tmp,'checkout-recovery',(await readdir(path.join(tmp,'checkout-recovery')))[0]),'utf8');assert.ok(!disk.includes(profile.name));assert.ok(!disk.includes(weights[0].photoUrl));assert.ok(!disk.includes(encrypted.recoveryKey));
 client='b'.repeat(48);assert.equal((await request('get','entitlement',{}, {session_id:session.id})).status,403);
 assert.equal((await request('get','checkout-restore',{}, {session_id:session.id},'f'.repeat(64))).status,410);
 assert.equal((await request('get','checkout-restore',{}, {session_id:'cs_test_other'},parsedSecret.token)).status,410);
 const restored=await request('get','checkout-restore',{}, {session_id:session.id},parsedSecret.token);assert.equal(restored.status,200);assert.equal(client,'a'.repeat(48));
 assert.equal((await request('get','checkout-restore',{}, {},parsedSecret.token)).status,200,'Cancellation without session placeholder');
 values.clear();assert.equal(getStoredProfile().isOnboardingCompleted,false);
 const data=await decryptCheckoutSnapshot(restored.data.encrypted,parsedSecret);await restoreCheckoutSnapshot(data);
 assert.equal(getStoredProfile().name,profile.name);assert.equal(getStoredProfile().isOnboardingCompleted,true);assert.equal(getStoredProfile().plan,'free','Restoring a snapshot must never grant Premium');assert.deepEqual(JSON.parse(storage.getItem('auraslim_verified_sessions')!),['cs_test_previous'],'Previous payments stay available for server verification');
 assert.deepEqual(JSON.parse(storage.getItem(STORAGE_KEYS.WEEKLY_PHOTOS)!),photos);assert.deepEqual(JSON.parse(storage.getItem(STORAGE_KEYS.WEIGHT_ENTRIES)!),weights);assert.deepEqual(JSON.parse(storage.getItem(STORAGE_KEYS.NUTRITION_ENTRIES)!),snapshot.nutrition);assert.equal(JSON.parse(storage.getItem(STORAGE_KEYS.WATER_LOGS)!)[0].amountMl,2500);assert.deepEqual(closedDays(storage,profile.id),[today]);
 assert.equal((await request('get','entitlement',{}, {session_id:session.id})).data.active,true);
 session.payment_status='unpaid';assert.equal((await request('get','entitlement',{}, {session_id:session.id})).data.active,false);
 assert.equal((await request('post','checkout-restore/complete',{sessionId:session.id},{},parsedSecret.token)).status,200);assert.equal(await readCheckoutRecovery(parsedSecret.token,session.id),null);
 const video=await request('post','checkout',{...body,plan:'progress_video',expectedPriceEur:3.99});assert.equal(video.data.returnTab,'photos');assert.equal(video.data.openVideo,true);assert.equal(new URL(created.success_url).searchParams.get('open_video'),'1');
 const recoveryFiles=await readdir(path.join(tmp,'checkout-recovery'));const expiredPath=path.join(tmp,'checkout-recovery',recoveryFiles[0]);const expired=JSON.parse(await readFile(expiredPath,'utf8'));expired.expires=Date.now()-1;await writeFile(expiredPath,JSON.stringify(expired));assert.equal(await readCheckoutRecovery(video.data.recoveryToken,session.id),null);
 // A genuinely shared store is necessary when checkout and return hit different instances.
 const actualFetch=globalThis.fetch, cloudObjects=new Map<string,string>();let metadataRequests=0;
 process.env.AURASLIM_BACKUP_BUCKET='private-auraslim-fixture';
 globalThis.fetch=async(input:any,init:any)=>{const url=new URL(String(input));if(url.hostname==='metadata.google.internal'){metadataRequests++;assert.equal(init.headers['Metadata-Flavor'],'Google');return Response.json({access_token:'fixture-runtime-token',expires_in:3600});}assert.equal(url.hostname,'storage.googleapis.com');assert.equal(init.headers.Authorization,'Bearer fixture-runtime-token');if(init.method==='POST'){assert.equal(url.searchParams.get('ifGenerationMatch'),'0');const name=url.searchParams.get('name')!;cloudObjects.set(name,init.body);return Response.json({name});}const name=decodeURIComponent(url.pathname.split('/o/')[1]);if(init.method==='DELETE'){cloudObjects.delete(name);return new Response(null,{status:204});}return cloudObjects.has(name)?new Response(cloudObjects.get(name),{headers:{'Content-Type':'application/json'}}):new Response(null,{status:404});};
 try {const cloudToken=newRecoveryToken();await saveCheckoutRecovery(cloudToken,session.id,'a'.repeat(48),encrypted.encrypted);assert.equal((await readCheckoutRecovery(cloudToken,session.id))?.session,session.id);assert.equal(metadataRequests,1);assert.equal((await readdir(path.join(tmp,'checkout-recovery'))).length,0,'Cloud backup does not depend on this instance filesystem');await removeCheckoutRecovery(cloudToken);assert.equal(await readCheckoutRecovery(cloudToken,session.id),null);assert.equal(cloudObjects.size,0);}finally{globalThis.fetch=actualFetch;delete process.env.AURASLIM_BACKUP_BUCKET;}
 // A storage failure must roll back the profile rather than creating a new account.
 const before=new Map(values);let fail=true;const originalSet=storage.setItem;
 storage.setItem=(key,value)=>{if(key===STORAGE_KEYS.WEEKLY_PHOTOS&&fail){fail=false;throw new Error('Quota fixture');}return originalSet(key,value);};
 try {await assert.rejects(restoreCheckoutSnapshot({...snapshot,profile:{...snapshot.profile,name:'Modified fixture'}}),/Quota fixture/);assert.deepEqual(values,before);}finally{storage.setItem=originalSet;}
 console.log('V4 verified: activity/BMR/goal calculations; calorie excess; honest day completion; mobile meal tabs; translation templates; encrypted full-data payment restore across a new browser context; cancellation, tamper, owner, expiry and unpaid protections.');
} finally {await rm(tmp,{recursive:true,force:true});}
